workflows:
  capacitor_android_release:
    name: Capacitor Android Build (Debug mode)
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 18
    scripts:
      - name: Install dependencies
        script: |
          npm ci || npm install
          npm install -D typescript
          npm install @capacitor/core @capacitor/cli --save
          npm run build || npx vite build
      - name: Generate Android project & sync
        script: |
          npx cap add android || true
          npx cap sync android
      - name: Build AAB (Debug)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleDebug
    artifacts:
      - android/app/build/outputs/bundle/debug/*.aab
